home_venues = {
"Abilene-Christian": "Moody Coliseum+Teague Center", 
"Air-Force": "Cadet Field House+Clune Arena", 
"Akron": "James A. Rhodes Arena", 
"Alabama": "Coleman Coliseum", 
"Alabama-AM": "Alabama A&M Events Center+T.M. Elmore Gymnasium", 
"Alabama-State": "Dunn–Oliver Acadome", 
"Albany": "SEFCU Arena", 
"Alcorn-State": "Davey L. Whitney Complex+Davey Whitney Complex", 
"American": "Bender Arena", 
"Appalachian-State": "Holmes Convocation Center", 
"Arizona": "McKale Center", 
"Arizona-State": "Desert Financial Arena", 
"Arkansas": "Bud Walton Arena", 
"Arkansas-Pine-Bluff": "K. L. Johnson Complex+H. O. Clemmons Arena", 
"Arkansas-State": "First National Bank Arena", 
"Army": "Christl Arena", 
"Auburn": "Neville Arena+Auburn Arena", 
"Austin-Peay": "Dunn Center+Winfield Dunn Center", 
"BYU": "Marriott Center", 
"Ball-State": "Worthen Arena", 
"Baylor": "Ferrell Center+Foster Pavilion", 
"Bellarmine": "Freedom Hall", 
"Belmont": "Curb Event Center Arena", 
"Bethune-Cookman": "Moore Gymnasium", 
"Binghamton": "Events Center", 
"Boise-State": "ExtraMile Arena", 
"Boston-College": "Silvio O. Conte Forum", 
"Boston-University": "Case Gym", 
"Bowling-Green": "Stroh Center", 
"Bradley": "Carver Arena", 
"Bradleywomen": "Renaissance Coliseum", 
"Brown": "Pizzitola Sports Center", 
"Bryant": "Chace Athletic Center", 
"Bucknell": "Sojka Pavilion", 
"Buffalo": "Alumni Arena", 
"Butler": "Hinkle Fieldhouse", 
"Cal-Poly": "Robert A. Mott Athletics Center", 
"Cal-State-Bakersfield": "Icardo Center", 
"Cal-State-Fullerton": "Titan Gym", 
"Cal-State-Northridge": "Premier America Credit Union Arena+Matadome", 
"California": "Haas Pavilion", 
"California-Baptist": "CBU Events Center", 
"Campbell": "John W. Pope Jr. Convocation Center", 
"Canisius": "Koessler Athletic Center", 
"Central-Arkansas": "Farris Center", 
"Central-Connecticut": "William H. Detrick Gymnasium", 
"Central-Michigan": "McGuirk Arena", 
"Charleston": "TD Arena", 
"Charleston-Southern": "Buccaneer Fieldhouse+McAlister Field House", 
"Charlotte": "Dale F. Halton Arena", 
"Chattanooga": "McKenzie Arena", 
"Chicago-State": "Emil and Patricia Jones Convocation Center", 
"Cincinnati": "Fifth Third Arena", 
"Clemson": "Littlejohn Coliseum", 
"Cleveland-State": "Wolstein Center", 
"Coastal-Carolina": "HTC Center", 
"Colgate": "Cotterell Court", 
"Colorado": "CU Events Center", 
"Colorado-State": "Moby Arena", 
"Columbia": "Levien Gymnasium", 
"Connecticut": "Gampel Pavilion+XL Center", 
"Coppin-State": "Physical Education Complex", 
"Cornell": "Newman Arena", 
"Creighton": "CHI Health Center Omaha", 
"Creightonwomen": "D. J. Sokol Arena", 
"Dartmouth": "Leede Arena", 
"Davidson": "John M. Belk Arena", 
"Dayton": "University of Dayton Arena+UD Arena", 
"DePaul": "Wintrust Arena[c]", 
"Delaware": "Bob Carpenter Center", 
"Delaware-State": "Memorial Hall", 
"Denver": "Magness Arena+Hamilton Gymnasium", 
"Detroit": "Calihan Hall", 
"Dixie-State": "Burns Arena", 
"Drake": "Knapp Center", 
"Drexel": "Daskalakis Athletic Center", 
"Duke": "Cameron Indoor Stadium", 
"Duquesne": "UPMC Cooper Fieldhouse", 
"East-Carolina": "Williams Arena at Minges Coliseum", 
"East-Tennessee-State": "Freedom Hall Civic Center", 
"Eastern-Illinois": "Lantz Arena", 
"Eastern-Kentucky": "Alumni Coliseum+McBrayer Arena", 
"Eastern-Michigan": "George Gervin GameAbove Center+Convocation Center", # Mark
"Eastern-Washington": "Reese Court", 
"Elon": "Schar Center", 
"Evansville": "Ford Center", 
"Evansvillewomen": "Meeks Family Fieldhouse at Carson Center", 
"FAU": "FAU Arena", 
"FGCU": "Alico Arena", 
"FIU": "Ocean Bank Convocation Center", 
"Fairfield": "Leo D. Mahoney Arena", 
"Fairleigh-Dickinson": "Rothman Center", 
"Florida": "O'Connell Center", 
"Florida-AM": "Al Lawson Center", 
"Florida-State": "Donald L. Tucker Civic Center", 
"Fordham": "Rose Hill Gymnasium", 
"Fresno-State": "Save Mart Center", 
"Furman": "Timmons Arena", 
"Gardner-Webb": "Paul Porter Arena", 
"George-Mason": "EagleBank Arena", 
"George-Washington": "Charles E. Smith Center", 
"Georgetown": "Capital One Arena", 
"Georgetownwomen": "McDonough Gymnasium", 
"Georgia": "Stegeman Coliseum", 
"Georgia-Southern": "Hanner Fieldhouse", 
"Georgia-State": "Georgia State Convocation Center", 
"Georgia-Tech": "Hank McCamish Pavilion", 
"Gonzaga": "McCarthey Athletic Center", 
"Grambling-State": "Fredrick C. Hobdy Assembly Center", 
"Grand-Canyon": "GCU Arena", 
"Green-Bay": "Resch Center", 
"GreenBaywomen": "Kress Events Center", 
"Hampton": "Hampton Convocation Center", 
"Hartford": "Chase Arena", 
"Harvard": "Lavietes Pavilion", 
"Hawaii": "Stan Sheriff Center", 
"High-Point": "Nido & Mariana Qubein Arena and Conference Center", 
"Hofstra": "Mack Sports Complex", 
"Holy-Cross": "Hart Center", 
"Houston": "Fertitta Center", 
"Houston-Baptist": "Sharp Gymnasium", 
"Howard": "Burr Gymnasium", 
"IUPUI": "Indiana Farmers Coliseum", 
"IUPUIwomen": "The Jungle", 
"Idaho": "Idaho Central Credit Union Arena", 
"Idaho-State": "Holt Arena", 
"IdahoStatewomen": "Reed Gym", 
"Illinois": "State Farm Center", 
"Illinois-State": "CEFCU Arena", 
"Incarnate-Word": "McDermott Center", 
"Indiana": "Simon Skjodt Assembly Hall", 
"Indiana-State": "Hulman Center", 
"Iona": "Hynes Athletic Center", 
"Iowa": "Carver–Hawkeye Arena", 
"Iowa-State": "Hilton Coliseum", 
"Jackson-State": "Williams Assembly Center", 
"Jacksonville": "Swisher Gymnasium", 
"Jacksonville-State": "Pete Mathews Coliseum", 
"James-Madison": "Atlantic Union Bank Center", 
"Kansas": "Allen Fieldhouse", 
"Kansas-State": "Bramlage Coliseum", 
"KansasCity": "Swinney Recreation Center", 
"Kennesaw-State": "KSU Convocation Center", 
"Kent-State": "Memorial Athletic and Convocation Center", 
"Kentucky": "Rupp Arena", 
"Kentuckywomen": "Memorial Coliseum", 
"LSU": "Pete Maravich Assembly Center", 
"La-Salle": "Tom Gola Arena", 
"Lafayette": "Kirby Sports Center", 
"Lamar": "Montagne Center", 
"Lehigh": "Stabler Arena", 
"Liberty": "Liberty Arena", 
"Lindenwood": "Robert F. Hyland Performance Arena", 
"Lipscomb": "Allen Arena", 
"Little-Rock": "Jack Stephens Center", 
"Long-Beach-State": "Walter Pyramid", 
"Long-Island": "Steinberg Wellness Center", 
"Longwood": "Willett Hall", 
"Louisiana": "Cajundome", 
"Louisiana-Tech": "Thomas Assembly Center", 
"Louisiana–Monroe": "Fant–Ewing Coliseum", 
"Louisville": "KFC Yum! Center", 
"Loyola-Chicago": "Joseph J. Gentile Arena", 
"Loyola-Maryland": "Reitz Arena", 
"Loyola-Marymount": "Gersten Pavilion", 
"Maine": "Cross Insurance Center", 
"Manhattan": "Draddy Gymnasium", 
"Marist": "McCann Arena", 
"Marquette": "Fiserv Forum", 
"Marquettewomen": "Al McGuire Center", 
"Marshall": "Cam Henderson Center", 
"Maryland": "Xfinity Center", 
"Maryland-Eastern-Shore": "Hytche Athletic Center", 
"UMass": "William D. Mullins Memorial Center", 
"McNeese": "The Legacy Center", 
"Memphis": "FedExForum", 
"Memphiswomen": "Elma Roane Fieldhouse", 
"Mercer": "Hawkins Arena", 
"Merrimack": "Hammel Court", 
"Miami-FL": "Watsco Center", 
"Miami-OH": "Millett Hall", 
"Michigan": "Crisler Center", 
"Michigan-State": "Breslin Student Events Center", 
"Middle-Tennessee": "Murphy Center", 
"Milwaukee": "UW–Milwaukee Panther Arena", 
"Milwaukeewomen": "Klotsche Center", 
"Minnesota": "Williams Arena", 
"Mississippi-State": "Humphrey Coliseum", 
"Mississippi-Valley-State": "Harrison HPER Complex", 
"Missouri": "Mizzou Arena", 
"Missouri-State": "Great Southern Bank Arena", 
"Monmouth": "OceanFirst Bank Center", 
"Montana": "Dahlberg Arena", 
"Montana-State": "Brick Breeden Fieldhouse", 
"Morehead-State": "Ellis Johnson Arena", 
"Morgan-State": "Talmadge L. Hill Field House", 
"Mount-Saint-Marys": "Knott Arena", 
"Murray-State": "CFSB Center", 
"NJIT": "Wellness and Events Center", 
"Navy": "Alumni Hall", 
"Nebraska": "Pinnacle Bank Arena", 
"Nevada": "Lawlor Events Center", 
"New-Hampshire": "Lundholm Gym", 
"New-Mexico": "The Pit", 
"New-Mexico-State": "Pan American Center", 
"New-Orleans": "Lakefront Arena", 
"Niagara": "Gallagher Center", 
"Nicholls": "Stopher Gymnasium", 
"Norfolk-State": "Joseph G. Echols Memorial Hall", 
"North-Alabama": "Flowers Hall", 
"North-Carolina": "Dean E. Smith Center", 
"North-Carolina-AT": "Corbett Sports Center", 
"North-Carolina-Central": "McDougald–McLendon Arena", 
"North-Carolina-State": "PNC Arena", 
"North-Dakota": "Betty Engelstad Sioux Center", 
"North-Dakota-State": "Scheels Center", 
"North-Florida": "UNF Arena", 
"North-Texas": "UNT Coliseum", 
"NorthCarolinaStatewomen": "Reynolds Coliseum", 
"NorthCarolinawomen": "Carmichael Arena", 
"Northeastern": "Matthews Arena", 
"Northeasternwomen": "Cabot Center", 
"Northern-Arizona": "Walkup Skydome", 
"Northern-Colorado": "Bank of Colorado Arena", 
"Northern-Illinois": "Convocation Center", 
"Northern-Iowa": "McLeod Center", 
"Northern-Kentucky": "Truist Arena", 
"Northwestern": "Welsh–Ryan Arena", 
"Northwestern-State": "Prather Coliseum", 
"Notre-Dame": "Edmund P. Joyce Center", 
"Oakland": "Athletics Center O'rena", 
"Ohio": "Convocation Center", 
"Ohio-State": "Value City Arena", 
"Oklahoma": "Lloyd Noble Center", 
"Oklahoma-State": "Gallagher-Iba Arena", 
"Old-Dominion": "Chartway Arena", 
"Ole-Miss": "The Sandy and John Black Pavilion at Ole Miss", 
"Omaha": "Baxter Arena", 
"Oral-Roberts": "Mabee Center", 
"Oregon": "Matthew Knight Arena", 
"Oregon-State": "Gill Coliseum", 
"Pacific": "Alex G. Spanos Center", 
"Penn": "Palestra", 
"Penn-State": "Bryce Jordan Center", 
"Pepperdine": "Firestone Fieldhouse", 
"Pittsburgh": "Petersen Events Center", 
"Portland": "Chiles Center", 
"Portland-State": "Viking Pavilion", 
"Prairie-View-AM": "William J. Nicks Building", 
"Presbyterian-College": "Templeton Physical Education Center", 
"Princeton": "Jadwin Gymnasium", 
"Providence": "Amica Mutual Pavilion", 
"Providencewomen": "Alumni Hall", 
"Purdue": "Mackey Arena", 
"Purdue-Fort-Wayne": "Hilliard Gates Sports Center", 
"Queens": "Curry Arena", 
"Quinnipiac": "People's United Center", 
"Radford": "Dedmon Center", 
"Rhode-Island": "Ryan Center", 
"Rice": "Tudor Fieldhouse", 
"Richmond": "Robins Center", 
"Rider": "Alumni Gymnasium", 
"Robert-Morris": "UPMC Events Center", 
"Rutgers": "Jersey Mike's Arena", 
"SIUE": "Vadalabene Center", 
"SMU": "Moody Coliseum", 
"Sacramento-State": "Hornets Nest", 
"Sacred-Heart": "William H. Pitt Center", 
"Saint-Bonaventure": "Reilly Center", 
"Saint-Francis-NY": "Pope Physical Education Center", 
"Saint-Francis-PA": "DeGol Arena", 
"Saint-Johns": "Carnesecca Arena+Madison Square Garden", 
"Saint-Josephs": "Hagan Arena", 
"Saint-Louis": "Chaifetz Arena", 
"Saint-Marys-College": "University Credit Union Pavilion", 
"Saint-Peters": "Yanitelli Center", 
"Saint-Thomas": "Schoenecker Arena", 
"Sam-Houston-State": "Bernard Johnson Coliseum", 
"Samford": "Pete Hanna Center", 
"San-Diego": "Jenny Craig Pavilion", 
"San-Diego-State": "Viejas Arena", 
"San-Francisco": "The Sobrato Center", 
"San-Jose-State": "Provident Credit Union Event Center", 
"Santa-Clara": "Leavey Center", 
"Seattle-University": "Redhawk Center", 
"Seton-Hall": "Prudential Center", 
"SetonHallwomen": "Walsh Gymnasium", 
"Siena": "MVP Arena", 
"Sienawomen": "Alumni Recreation Center", 
"South-Alabama": "Mitchell Center", 
"South-Carolina": "Colonial Life Arena", 
"South-Carolina-State": "SHM Memorial Center", 
"South-Carolina-Upstate": "G. B. Hodge Center", 
"South-Dakota": "Sanford Coyote Sports Center", 
"South-Dakota-State": "Frost Arena", 
"South-Florida": "Yuengling Center", 
"Southeast-Missouri": "Show Me Center", 
"Southeastern-Louisiana": "University Center", 
"Southern": "F. G. Clark Center", 
"Southern-Illinois": "Banterra Center", 
"Southern-Miss": "Reed Green Coliseum", 
"Southern-Utah": "America First Event Center", 
"SouthernIndiana": "Screaming Eagles Arena", 
"St.John'swomen": "Carnesecca Arena", 
"Stanford": "Maples Pavilion", 
"Stephen-F-Austin": "William R. Johnson Coliseum", 
"Stetson": "Edmunds Center", 
"Stonehill": "Merkert Gymnasium", 
"Stony-Brook": "Island Federal Credit Union Arena", 
"Syracuse": "JMA Wireless Dome", 
"TCU": "Schollmaier Arena", 
"Tarleton-State": "Wisdom Gymnasium", 
"Temple": "Liacouras Center[a]", 
"Tennessee": "Thompson–Boling Arena", 
"Tennessee-Martin": "Kathleen and Tom Elam Center", 
"Tennessee-State": "Gentry Complex", 
"Tennessee-Tech": "Eblen Center", 
"Texas": "Moody Center", 
"Texas-AM": "Reed Arena", 
"Texas-AM-Corpus-Christi": "American Bank Center Arena[h]", 
"Texas-Southern": "Health and Physical Education Arena", 
"Texas-State": "Strahan Arena", 
"Texas-Tech": "United Supermarkets Arena", 
"TexasA&M–Commerce": "Texas A&M–Commerce Field House", 
"The-Citadel": "McAlister Field House", 
"Toledo": "Savage Arena", 
"Towson": "SECU Arena", 
"Troy": "Trojan Arena", 
"Tulane": "Devlin Fieldhouse", 
"Tulsa": "Reynolds Center", 
"UAB": "Bartow Arena", 
"UC-Davis": "The Pavilion at ARC", 
"UC-Irvine": "Bren Events Center", 
"UC-Riverside": "Student Recreation Center Arena", 
"UC-San-Diego": "RIMAC Arena", 
"UC-Santa-Barbara": "UC Santa Barbara Events Center", 
"UCF": "Addition Financial Arena", 
"UCLA": "Pauley Pavilion", 
"UIC": "Credit Union 1 Arena", 
"ULM": "Fant–Ewing Coliseum", 
"UMBC": "Chesapeake Employers Insurance Arena", 
"UMKC": "Swinney Recreation Center", 
"UMass-Lowell": "Tsongas Center+Costello Athletic Center", 
"UNC-Asheville": "Kimmel Arena", 
"UNCG": "Greensboro Coliseum", 
"UNCW": "Trask Coliseum", 
"UNLV": "Thomas & Mack Center", 
"UNLVwomen": "Cox Pavilion", 
"USC": "Galen Center", 
"UTA": "College Park Center", 
"UTEP": "Don Haskins Center", 
"UTRGV": "UTRGV Fieldhouse", 
"UTSA": "Convocation Center", 
"Utah": "Jon M. Huntsman Center", 
"Utah-State": "Smith Spectrum", 
"Utah-Valley": "UCCU Center", 
"VCU": "Siegel Center", 
"VMI": "Cameron Hall", 
"Valparaiso": "Athletics–Recreation Center", 
"Vanderbilt": "Memorial Gymnasium", 
"Vermont": "Patrick Gym", 
"Villanova": "Finneran Pavilion[f]", 
"Virginia": "John Paul Jones Arena", 
"Virginia-Tech": "Cassell Coliseum", 
"Wagner": "Spiro Sports Center", 
"Wake-Forest": "Lawrence Joel Veterans Memorial Coliseum", 
"Washington": "Alaska Airlines Arena at Hec Edmundson Pavilion", 
"Washington-State": "Beasley Coliseum", 
"Weber-State": "Dee Events Center", 
"West-Virginia": "WVU Coliseum", 
"Western-Carolina": "Ramsey Center", 
"Western-Illinois": "Western Hall", 
"Western-Kentucky": "E. A. Diddle Arena", 
"Western-Michigan": "University Arena", 
"Wichita-State": "Charles Koch Arena[b]", 
"William-Mary": "Kaplan Arena", 
"Winthrop": "Winthrop Coliseum", 
"Wisconsin": "Kohl Center", 
"Wofford": "Jerry Richardson Indoor Stadium", 
"Wright-State": "Nutter Center", 
"Wyoming": "Arena-Auditorium", 
"Xavier": "Cintas Center", 
"Yale": "John J. Lee Amphitheater", 
"Youngstown-State": "Beeghly Center", 
}

away_arenas = {
    "Orleans Arena",
"T-Mobile Arena",
"Ocean Center",
"Hertz Arena",
"Viejas Arena",
"Legacy Arena at BJCC",
"HP Field House",
"Amelie Arena",
"State Farm Arena",
"Bridgestone Arena",
"Bankers Life Fieldhouse",
"Mitchell Center",
"Davey L. Whitney Complex",
"Davey Whitney Complex",
"AT&T Center",
"Mohegan Sun Arena",
"T-Mobile Center",
"Simmons Bank Arena",
"Hinkle Fieldhouse",
"McArthur Center",
"Gainbridge Fieldhouse",
"Imperial Arena",
"Dickies Arena",
"Moore Gymnasium",
"TD Arena",
"Moda Center",
"Comerica Center",
"Silvio Conte Forum",
"Suncoast Credit Union Arena",
"Cintas Center",
"Hard Rock Hotel Riviera Maya",
"Michelob Ultra Arena",
"Stan Sheriff Center",
"Vivint Smart Home Arena",
"Gill Coliseum",
"Titan Gym",
"Swisher Gymnasium",
"KeyBank Center",
"William H. Detrick Gymnasium",
"Spectrum Center",
"Baha Mar Convention Center",
"Ford Center at the Star",
"Halton Arena",
"Barclays Center",
"Indiana Farmers Coliseum",
"UVI Sports & Fitness Center",
"Bramlage Coliseum",
"Sanford Pentagon",
"UNT Coliseum",
"Capital One Arena",
"Harrah's Cherokee Center",
"Robins Center",
"UTSA Convocation Center",
"Atlantic Union Bank Center",
"Madison Square Garden",
"Matadome",
"Stratis Arena at the Rothman Center",
"Al Lawson Center",
"GSU Sports Arena",
"Footprint Center",
"Climate Pledge Arena",
"Chase Center",
"Resch Center",
"Mack Sports Complex",
"PPG Paints Arena",
"Simon Skjodt Assembly Hall",
"Leonard E. Merrell Center",
"Wolstein Center",
"Lucas Oil Stadium",
"South Padre Island Convention Center",
"Alice P. McDermott Convocation Center",
"The HTC Center",
"UBS Arena",
"Caesars Superdome",
"Moe Kent Family Field House",
"Avron B. Fogelman Arena in the Devlin Fieldhouse",
"The Palestra",
"Carnesecca Arena",
"Steinberg Wellness Center",
"Cajundome",
"Hartsell Arena",
"Brookshire Grocery Arena",
"Fiserv Forum",
"H&HP Complex",
"Hammel Court",
"United Center",
"Mackey Arena",
"Bon Secours Wellness Arena",
"Mississippi Coliseum",
"Robert W. Harrison Complex",
"First National Bank Arena",
"JSerra Pavillion",
"Rock Hill Sports & Event Center",
"Walter E. Washington Convention Center",
"Raider Arena",
"Paul Porter Arena",
"Don Haskins Center",
"FAU Arena",
"Enterprise Center",
"Little Caesars Arena",
"BOK Center",
"Ralston Sports and Events Center",
"Chiles Center",
"Greensboro Coliseum",
"Wells Fargo Center",
"Allen County War Memorial Coliseum",
"Alumni Hall",
"University of Dayton Arena",
"Jersey Mike’s Arena",
"Stuart C. Siegel Center",
"Pope Physical Education Center",
"Toyota Center",
"UNF Arena",
"Bruin Arena",
"War Memorial Gymnasium",
"Ability 360 Sports and Fitness Center",
"Pensacola Bay Center",
"Martin Carter Gymnasium",
"Alico Arena",
"Kimmel Arena",
"The Pavilion",
"Thomas Assembly Center",
"Dahlberg Arena",
"Sharp Gymnasium",
"Millett Hall",
"Intrust Bank Arena",
"Bojangles Coliseum",
"Thomas & Mack Center"
}


problematic_team_names = {
    "AbileneChristian": "Abilene-Christian",
    "AirForce": "Air-Force",
    "Akron": "Akron",
    "Alabama": "Alabama",
    "AlabamaA&M": "Alabama-AM",
    "AlabamaState": "Alabama-State",
    "Albany": "Albany",
    "AlcornState": "Alcorn-State",
    "American": "American",
    "AppalachianState": "Appalachian-State",
    "Arizona": "Arizona",
    "ArizonaState": "Arizona-State",
    "Arkansas": "Arkansas",
    "Arkansas-PineBluff": "Arkansas-Pine-Bluff",
    "ArkansasState": "Arkansas-State",
    "Army": "Army",
    "Auburn": "Auburn",
    "AustinPeay": "Austin-Peay",
    "BallState": "Ball-State",
    "Baylor": "Baylor",
    "Bellarmine": "Bellarmine",
    "Belmont": "Belmont",
    "Bethune-Cookman": "Bethune-Cookman",
    "Binghamton": "Binghamton",
    "BoiseState": "Boise-State",
    "BostonCollege": "Boston-College",
    "BostonUniversity": "Boston-University",
    "BowlingGreen": "Bowling-Green",
    "Bradleymen": "Bradley",
    "Brown": "Brown",
    "Bryant": "Bryant",
    "Bucknell": "Bucknell",
    "Buffalo": "Buffalo",
    "Butler": "Butler",
    "BYU": "BYU",
    "CalPoly": "Cal-Poly",
    "CalStateBakersfield": "Cal-State-Bakersfield",
    "CalStateFullerton": "Cal-State-Fullerton",
    "CalStateNorthridge": "Cal-State-Northridge",
    "California": "California",
    "CaliforniaBaptist": "California-Baptist",
    "Campbell": "Campbell",
    "Canisius": "Canisius",
    "CentralArkansas": "Central-Arkansas",
    "CentralConnecticut": "Central-Connecticut",
    "CentralMichigan": "Central-Michigan",
    "Charleston": "Charleston",
    "CharlestonSouthern": "Charleston-Southern",
    "Charlotte": "Charlotte",
    "Chattanooga": "Chattanooga",
    "ChicagoState": "Chicago-State",
    "Cincinnati": "Cincinnati",
    "Clemson": "Clemson",
    "ClevelandState": "Cleveland-State",
    "CoastalCarolina": "Coastal-Carolina",
    "Colgate": "Colgate",
    "Colorado": "Colorado",
    "ColoradoState": "Colorado-State",
    "Columbia": "Columbia",
    "UConn": "Connecticut",
    "CoppinState": "Coppin-State",
    "Cornell": "Cornell",
    "Creightonmen": "Creighton",
    "Dartmouth": "Dartmouth",
    "Davidson": "Davidson",
    "Dayton": "Dayton",
    "Delaware": "Delaware",
    "DelawareState": "Delaware-State",
    "Denver": "Denver",
    "DePaul": "DePaul",
    "DetroitMercy": "Detroit",
    "UtahTech[26]": "Dixie-State",
    "Drake": "Drake",
    "Drexel": "Drexel",
    "Duke": "Duke",
    "Duquesne": "Duquesne",
    "EastCarolina": "East-Carolina",
    "EastTennesseeState": "East-Tennessee-State",
    "EasternIllinois": "Eastern-Illinois",
    "EasternKentucky": "Eastern-Kentucky",
    "EasternMichigan": "Eastern-Michigan",
    "EasternWashington": "Eastern-Washington",
    "Elon": "Elon",
    "Evansvillemen": "Evansville",
    "Fairfield": "Fairfield",
    "FairleighDickinson": "Fairleigh-Dickinson",
    "FloridaAtlantic": "FAU",
    "FloridaGulfCoast": "FGCU",
    "FIU": "FIU",
    "Florida": "Florida",
    "FloridaA&M": "Florida-AM",
    "FloridaState": "Florida-State",
    "Fordham": "Fordham",
    "FresnoState": "Fresno-State",
    "Furman": "Furman",
    "Gardner–Webb": "Gardner-Webb",
    "GeorgeMason": "George-Mason",
    "GeorgeWashington": "George-Washington",
    "Georgetownmen": "Georgetown",
    "Georgia": "Georgia",
    "GeorgiaSouthern": "Georgia-Southern",
    "GeorgiaState": "Georgia-State",
    "GeorgiaTech": "Georgia-Tech",
    "Gonzaga": "Gonzaga",
    "Grambling": "Grambling-State",
    "GrandCanyon": "Grand-Canyon",
    "GreenBaymen": "Green-Bay",
    "Hampton": "Hampton",
    "Hartford": "Hartford",
    "Harvard": "Harvard",
    "HawaiimenHawaiiwomen": "Hawaii",
    "HighPoint": "High-Point",
    "Hofstra": "Hofstra",
    "HolyCross": "Holy-Cross",
    "Houston": "Houston",
    "HoustonBaptist": "Houston-Baptist",
    "Howard": "Howard",
    "Idaho": "Idaho",
    "IdahoStatemen": "Idaho-State",
    "Illinois": "Illinois",
    "IllinoisState": "Illinois-State",
    "IncarnateWord": "Incarnate-Word",
    "Indiana": "Indiana",
    "IndianaState": "Indiana-State",
    "Iona": "Iona",
    "Iowa": "Iowa",
    "IowaState": "Iowa-State",
    "IUPUImen": "IUPUI",
    "JacksonState": "Jackson-State",
    "Jacksonville": "Jacksonville",
    "JacksonvilleState": "Jacksonville-State",
    "JamesMadison": "James-Madison",
    "Kansas": "Kansas",
    "KansasState": "Kansas-State",
    "KennesawState": "Kennesaw-State",
    "KentState": "Kent-State",
    "Kentuckymen[g]": "Kentucky",
    "LaSalle": "La-Salle",
    "Lafayette": "Lafayette",
    "Lamar": "Lamar",
    "Lehigh": "Lehigh",
    "Liberty": "Liberty",
    "Lipscomb": "Lipscomb",
    "LittleRock": "Little-Rock",
    "LongBeachState": "Long-Beach-State",
    "LIU": "Long-Island",
    "Longwood": "Longwood",
    "Louisiana": "Louisiana",
    "LouisianaTech": "Louisiana-Tech",
    "Louisville": "Louisville",
    "LoyolaChicago": "Loyola-Chicago",
    "Loyola(Maryland)": "Loyola-Maryland",
    "LoyolaMarymount": "Loyola-Marymount",
    "LSU": "LSU",
    "Maine": "Maine",
    "Manhattan": "Manhattan",
    "Marist": "Marist",
    "Marquettemen": "Marquette",
    "Marshall": "Marshall",
    "Maryland": "Maryland",
    "MarylandEasternShore": "Maryland-Eastern-Shore",
    "McNeese": "McNeese",
    "Memphis": "Memphis",
    "Mercer": "Mercer",
    "Merrimack": "Merrimack",
    "Miami(FL)": "Miami-FL",
    "Miami(Ohio)": "Miami-OH",
    "Michigan": "Michigan",
    "MichiganState": "Michigan-State",
    "MiddleTennessee": "Middle-Tennessee",
    "Milwaukeemen": "Milwaukee",
    "Minnesota": "Minnesota",
    "MississippiState": "Mississippi-State",
    "MississippiValleyState": "Mississippi-Valley-State",
    "Missouri": "Missouri",
    "MissouriState": "Missouri-State",
    "Monmouth": "Monmouth",
    "Montana": "Montana",
    "MontanaState": "Montana-State",
    "MoreheadState": "Morehead-State",
    "MorganState": "Morgan-State",
    "MountSt.Mary's": "Mount-Saint-Marys",
    "MurrayState": "Murray-State",
    "Navy": "Navy",
    "Nebraska": "Nebraska",
    "Nevada": "Nevada",
    "NewHampshire": "New-Hampshire",
    "NewMexico": "New-Mexico",
    "NewMexicoState": "New-Mexico-State",
    "NewOrleans": "New-Orleans",
    "Niagara": "Niagara",
    "Nicholls": "Nicholls",
    "NJIT": "NJIT",
    "NorfolkState": "Norfolk-State",
    "NorthAlabama": "North-Alabama",
    "NorthCarolinamen": "North-Carolina",
    "NorthCarolinaA&T": "North-Carolina-AT",
    "NorthCarolinaCentral": "North-Carolina-Central",
    "NorthCarolinaStatemen": "North-Carolina-State",
    "NorthDakota": "North-Dakota",
    "NorthDakotaState": "North-Dakota-State",
    "NorthFlorida": "North-Florida",
    "NorthTexas": "North-Texas",
    "Northeasternmen": "Northeastern",
    "NorthernArizona": "Northern-Arizona",
    "NorthernColorado": "Northern-Colorado",
    "NorthernIllinois": "Northern-Illinois",
    "NorthernIowa": "Northern-Iowa",
    "NorthernKentucky": "Northern-Kentucky",
    "Northwestern": "Northwestern",
    "NorthwesternState": "Northwestern-State",
    "NotreDame": "Notre-Dame",
    "Oakland": "Oakland",
    "Ohio": "Ohio",
    "OhioState": "Ohio-State",
    "Oklahoma": "Oklahoma",
    "OklahomaState": "Oklahoma-State",
    "OldDominion": "Old-Dominion",
    "OleMiss": "Ole-Miss",
    "Omaha": "Omaha",
    "OralRoberts": "Oral-Roberts",
    "Oregon": "Oregon",
    "OregonState": "Oregon-State",
    "Pacific": "Pacific",
    "Penn": "Penn",
    "PennState": "Penn-State",
    "Pepperdine": "Pepperdine",
    "Pittsburgh": "Pittsburgh",
    "Portland": "Portland",
    "PortlandState": "Portland-State",
    "PrairieViewA&M": "Prairie-View-AM",
    "Presbyterian": "Presbyterian-College",
    "Princeton": "Princeton",
    "Providencemen": "Providence",
    "Purdue": "Purdue",
    "PurdueFortWayne": "Purdue-Fort-Wayne",
    "Quinnipiac": "Quinnipiac",
    "Radford": "Radford",
    "RhodeIsland": "Rhode-Island",
    "Rice": "Rice",
    "Richmond": "Richmond",
    "Rider": "Rider",
    "RobertMorris": "Robert-Morris",
    "Rutgers": "Rutgers",
    "SacramentoState": "Sacramento-State",
    "SacredHeart": "Sacred-Heart",
    "St.Bonaventure": "Saint-Bonaventure",
    "St.FrancisBrooklyn": "Saint-Francis-NY",
    "SaintFrancis(PA)": "Saint-Francis-PA",
    "St.John'smen": "Saint-Johns",
    "SaintJoseph's": "Saint-Josephs",
    "SaintLouis": "Saint-Louis",
    "SaintMary's": "Saint-Marys-College",
    "SaintPeter's": "Saint-Peters",
    "St.Thomas": "Saint-Thomas",
    "SamHouston": "Sam-Houston-State",
    "Samford": "Samford",
    "SanDiego": "San-Diego",
    "SanDiegoState": "San-Diego-State",
    "SanFrancisco": "San-Francisco",
    "SanJoseState": "San-Jose-State",
    "SantaClara": "Santa-Clara",
    "Seattle": "Seattle-University",
    "SetonHallmen": "Seton-Hall",
    "Sienamen": "Siena",
    "SIUEdwardsville": "SIUE",
    "SMU": "SMU",
    "SouthAlabama": "South-Alabama",
    "SouthCarolina": "South-Carolina",
    "SouthCarolinaState": "South-Carolina-State",
    "USCUpstate": "South-Carolina-Upstate",
    "SouthDakota": "South-Dakota",
    "SouthDakotaState": "South-Dakota-State",
    "SouthFlorida": "South-Florida",
    "SoutheastMissouriState": "Southeast-Missouri",
    "SoutheasternLouisiana": "Southeastern-Louisiana",
    "Southern": "Southern",
    "SouthernIllinois": "Southern-Illinois",
    "SouthernMiss": "Southern-Miss",
    "SouthernUtah": "Southern-Utah",
    "Stanford": "Stanford",
    "StephenF.Austin": "Stephen-F-Austin",
    "Stetson": "Stetson",
    "StonyBrook": "Stony-Brook",
    "Syracuse": "Syracuse",
    "Tarleton": "Tarleton-State",
    "TCU": "TCU",
    "Temple": "Temple",
    "Tennessee": "Tennessee",
    "TennesseeState": "Tennessee-State",
    "TennesseeTech": "Tennessee-Tech",
    "Tennessee-Martin": "Tennessee-Martin",
    "Texas": "Texas",
    "TexasA&M": "Texas-AM",
    "TexasA&M-CorpusChristi": "Texas-AM-Corpus-Christi",
    "TexasSouthern": "Texas-Southern",
    "TexasState": "Texas-State",
    "TexasTech": "Texas-Tech",
    "TheCitadel": "The-Citadel",
    "Toledo": "Toledo",
    "Towson": "Towson",
    "Troy": "Troy",
    "Tulane": "Tulane",
    "Tulsa": "Tulsa",
    "UAB": "UAB",
    "UCDavis": "UC-Davis",
    "UCIrvine": "UC-Irvine",
    "UCRiverside": "UC-Riverside",
    "UCSanDiego": "UC-San-Diego",
    "UCSantaBarbara": "UC-Santa-Barbara",
    "UCF": "UCF",
    "UCLA": "UCLA",
    "UIC": "UIC",
    "ULM": "ULM",
    "UMass": "UMass",
    "UMassLowell": "UMass-Lowell",
    "UMBC": "UMBC",
    "UMKC": "UMKC",
    "UNCAsheville": "UNC-Asheville",
    "UNCGreensboro": "UNCG",
    "UNCWilmington": "UNCW",
    "UNLVmen": "UNLV",
    "USC": "USC",
    "UTArlington": "UTA",
    "Utah": "Utah",
    "UtahState": "Utah-State",
    "UtahValley": "Utah-Valley",
    "UTEP": "UTEP",
    "UTRGV": "UTRGV",
    "UTSA": "UTSA",
    "Valparaiso": "Valparaiso",
    "Vanderbilt": "Vanderbilt",
    "VirginiaCommonwealth": "VCU",
    "Vermont": "Vermont",
    "Villanova": "Villanova",
    "Virginia": "Virginia",
    "VirginiaTech": "Virginia-Tech",
    "VMI": "VMI",
    "Wagner": "Wagner",
    "WakeForest": "Wake-Forest",
    "Washington": "Washington",
    "WashingtonState": "Washington-State",
    "WeberState": "Weber-State",
    "WestVirginia": "West-Virginia",
    "WesternCarolina": "Western-Carolina",
    "WesternIllinois": "Western-Illinois",
    "WesternKentucky": "Western-Kentucky",
    "WesternMichigan": "Western-Michigan",
    "WichitaState": "Wichita-State",
    "William&Mary": "William-Mary",
    "Winthrop": "Winthrop",
    "Wisconsin": "Wisconsin",
    "Wofford": "Wofford",
    "WrightState": "Wright-State",
    "Wyoming": "Wyoming",
    "Xavier": "Xavier",
    "Yale": "Yale",
    "YoungstownState": "Youngstown-State"
}